# generated by datamodel-codegen:
#   filename:  anibridge_mappings.schema.json
#   timestamp: 2026-04-08T11:51:26+00:00
#
# Hand-extended to support the dynamic pattern-keyed mapping entries
# (provider:id[:scope] → target:id[:scope] → episode-range dict).

from __future__ import annotations

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field

# See mapings schema: 
# https://github.com/anibridge/anibridge-mappings?tab=readme-ov-file#mappings-schema

# Episode range maps: source range → target range (or None to explicitly unmap)
# Source key format:  \d+(-\d*)?    e.g. "1", "1-13", "1-"
# Target value format: same, optionally with comma-joined ranges and |offset
EpisodeRangeMap = dict[str, str | None]

# A single target descriptor (provider:id[:scope]) and its episode map
TargetEntry = dict[str, EpisodeRangeMap]

# The full mapping file: each key is a source descriptor; value is a TargetEntry.
# The $meta / $includes / $schema special keys are handled as typed fields.
RawMappings = dict[str, TargetEntry]


class FieldMeta(BaseModel):
    model_config = ConfigDict(extra="allow")
    schema_version: str | None = None
    generated_on: AwareDatetime | None = None


class AnibridgeMappings(BaseModel):
    """Top-level AniBridge v3 mappings model.

    The dynamic mapping entries (``provider:id[:scope]`` keys) are accessible
    via ``model_extra`` after validation.  Use ``extra="allow"`` so Pydantic
    stores them without raising validation errors.

    Example::

        data = AnibridgeMappings.model_validate_json(path.read_text())
        tvdb_entry = data.model_extra["tvdb_show:267440:s0"]
        # → {"anilist:119113": {"31": "1"}, ...}
    """

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    field_meta: FieldMeta | None = Field(None, alias="$meta")
    field_includes: list[str] | None = Field(None, alias="$includes")
    field_schema: str | None = Field(None, alias="$schema")
