name: Build

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main

jobs:
  build_sdist_and_wheel:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true
      - name: Setup Python versions
        uses: actions/setup-python@v6
        with:
          python-version: |
            3.11
            3.12
            3.13
            3.14
      - name: Install tox
        run: pip install tox
      - name: Build and validate package
        run: tox
